### ISSUE TITLE
NEW ARTICLE: Cross device import of email settings feature  (QR code, etc)

### ISSUE THREAD

**Issue by rtanglao** [thundernest/knowledgebase-issues#158]
* SUMO KB article with the material from https://github.com/thunderbird/thunderbird-android/issues/8109
* SUMO KB Article:  [Import settings and data into Thunderbird for Android](https://support.mozilla.org/en-US/kb/thunderbird-android-import)
*  bug [1926905: Export for Mobile:Change to 2. Go to Settings (instead of 'settings')](https://bugzilla.mozilla.org/show_bug.cgi?id=1926905):  <-- desktop typo bug so minor :-) not fixed in 128.4.0 Perhaps later releases? Like 133 or later? I am guessing the entire screen will be revamped!
### Checklist

- [ ] Possibly document: front-facing cameras like Chromebook not supported. see comment below: https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770702
- [ ] Possibly document high contrast mode issues that were fixed in late 2024 (128.4.3, as of this writing we are at 128.7.0, see Martin's comment https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770667
- [ ] Document fix for [bug 1928317: export for mobile - need option to disable this feature](https://bugzilla.mozilla.org/show_bug.cgi?id=1928317) and also [bug 1928232: Missing Windows account password request in "Export for Mobile" feature](https://bugzilla.mozilla.org/show_bug.cgi?id=1928232) <-- Update it's in 128.4.2 (see 1928317 comment: `Since version 128.4.2 "Include all accounts passwords" is hidden if ("pref.privacy.disable_button.view_passwords", true); is set in C:\Program Files\Mozilla Thunderbird\thunderbird.cfg This is exactly what we wanted :-)`)
- [x] Document [Bug 1928234: QR code colors can get inverted in high contrast mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1928234), since Thunderbird for Android currently fails to scan QR codes when this happens, so you'd have to disable high contrast mode to make it work atm. ([Full details](https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770667); fix will be in 128.4.2 or maybe one later) <-- fixed in November 2024
- [x] Clarify: [only 1 QR code is shown at a time](https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770551)
- [x] Fix;: Section: Import the Desktop settings into Thunderbird for Android / First run as per [ketti's comment](https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770560), `Scanned 1 of 2` on Android and then click `next` on Desktop
- [x] Document: [The Android apps currently don't support exporting passwords via the export to file option.](https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770571)
- [x] Document `Import from file` flow
- [x] Document [Martin's feedback about only default identity for SMTP server is supported: we just only export the outgoing server of the default identity. And that server has to be an SMTP server.](https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770501)
- [x] [Document multiple QR codes when you have more than 3 accounts](https://thunderbird.topicbox.com/groups/android-beta/T5f5ca6c4ab1e1d28-M66ac7caf4bcb6267383242f3)
- [x] Document not supported: Gssap, Ntlm, TlsCertificate (technically, this is supported, but not really with the import flow). TryStartTls,
- [x] Document import from K-9
    - [x] Document the fact that if you don't have an email account setup in K-9 then import from K-9 will have an error message <-- this is wrong in beta4 at least; there is no error message. It just imports the general settings since by default `General settings` is ticked
- [x] Document import from Thunderbird Desktop
- [x] Add screenshots from both Desktop and Android once the feature has stabilized.
- [x] Change the metadata so that this article is applicable to Desktop as well as Android
- [x] Beta 4 won't have `Import Settings` on the first screen. Remove it from the article when Beta 4 is released on Monday October 21, 2024
- [ ] Document the fact that there is no sync it's a one time import
- [x] Document that it's only in Thundebird for Android beta 4 and Thunderbird Desktop 128.4.0<del>128.3.4</del> or newer
- [x] Document: first run doesn't use the hamburger menu to get to the import dialogs but subsequent runs do (you have to tap on `Get Started` ([screenshot](https://flic.kr/p/2qpvjAH)) and then the [first run second screen](https://flic.kr/p/2qpCaiy) has `Import settings` (from desktop), `Add an email account now` and `Import your account settings now` and the wording of the `import from application` buttons is slightly different First Run: `Import your account settings now`. Subsequent runs: `Import from app`

### References
* [bug: 1919786 Provide List of accounts which meet eligibility criteria](https://bugzilla.mozilla.org/show_bug.cgi?id=1919786) <-- sadly POP is supported :-) not supported: Gssap, Ntlm,  TlsCertificate (technically, this is supported, but not really with the import flow). TryStartTls, More than one outgoing server is not supported, Non-ASCII email addresses are not supported
* google doc: [Cross Device Import - Scope of Work](https://docs.google.com/document/d/1siSwPzNPkwq4BL5G3z2K4zzRJuL9N9zbPodMOggXbdA/edit#heading=h.kkv9ni3l1s15)

**Comment by rtanglao** [comment]
* stub is live at: https://support.mozilla.org/kb/thunderbird-android-import ; rev [286063](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/286063)

**Comment by rtanglao** [comment]
* from toby in Matrix: The desktop side should now all be in review. If you want to test the full integration you can get the following desktop builds: [Linux](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/IdjcrJtQTj26DGVyYCAgig/runs/0/artifacts/public/build/target.tar.bz2) [Mac OS](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/SZsu_HdBRLCYtZ1QLODjLQ/runs/0/artifacts/public/build/target.dmg) [Windows](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/W-rm6aWASI2UKeX29-0eAg/runs/0/artifacts/public/build/setup.exe) (from https://treeherder.mozilla.org/jobs?repo=try-comm-central&revision=0be438f079a31ed91ff2e4cdf41336a02ef1f4f5). These builds have everything, except that you can't search for the qr export pane in the search bar of the settings, but that should be of little concern for now (if absolutely needed I can run a new try build, but I've been holding off since we have lots of extra failing tests currently, so value is limited :( ). You can get to the new shiny UI by clicking on the app menu in the top right, then click "Settings" and you should see "Export for Mobile" as a category in the tab that opens.

**Comment by rtanglao** [comment]
* October 15, 2024 Daily doesn't have the patch to disable the `Include all accounts passwords` when all the accounts are OAuth. Plan is for it to be in the Oct 16 TB Daily build

**Comment by rtanglao** [comment]
* @wsmwk @dannycolin @tobypilling @kewisch  Would love your feedback on [revision 286785](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/286785) Please note that screenshots will be added once the feature has stabilized which hopefully is this week e.g. October 18 or so?

**Comment by freaktechnik** [comment]
Feedback: We link to the page from Desktop with the copy of "Not seeing all your accounts? Some accounts may be disabled because they are not supported by Thunderbird for Android. <support link here>". As such I'd expect the page to mention more specifically why accounts might not be shown? (Do you think it's better to state the unsupported stuff vs. stating what's supported, since the latter makes it sound like less?)

**Comment by rtanglao** [comment]
> Feedback: We link to the page from Desktop with the copy of "Not seeing all your accounts? Some accounts may be disabled because they are not supported by Thunderbird for Android. ".  <-- @freaktechnik what page is that? URL please :-) !

**Comment by freaktechnik** [comment]
The revision you linked above, so /kb/thunderbird-android-import

**Comment by rtanglao** [comment]
> The revision you linked above, so /kb/thunderbird-android-import

so document what's not supported i.e. Gssap, Ntlm, TlsCertificate @freaktechnik ?

**Comment by freaktechnik** [comment]
> so document what's not supported i.e. Gssap, Ntlm, TlsCertificate @freaktechnik ?

That's what I'd expect to learn about given the copy we have in Thunderbird Desktop when linking to that article. We also require an SMTP server to be configured and the email address (of the identity - currently only the default identity even though we export multiple identities; potential bug) to be ASCII. And of course only IMAP/POP3 mail accounts can be exported.

**Comment by rtanglao** [comment]
* multiple QR codes revision: revision [287202](https://support.mozilla.org/en-US/kb/thunderbird-android-import/review/287202)
* import from App i.e. K-9 revision [287208](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287208) and [287209](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287209)
* add Table of contents, some minor changes: revision [287210](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287210)
* added desktop screenshot: revision [287225](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287225)

**Comment by rtanglao** [comment]
* oh and i added the What's not supported @freaktechnik , please check it out: https://support.mozilla.org/en-US/kb/thunderbird-android-import feedback welcome!

**Comment by rtanglao** [comment]
* revision: [287324](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287324): fix typos and links
* revision: [287325](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287325): document first run differences
* revision [287327](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287327): add screenshot showing: QR code export from desktop 
* revision [287328](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287328): Remove bottom left confirmation language because it doesn't apply to the most common case which is just 1 QR code. 
* revision [287329](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287329): add `Open Thunderbird Desktop` to `Export Thunderbird Desktop settings`

**Comment by rtanglao** [comment]
* revision [287382](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287382): export to mobile is in 128.4.0 or later not 128.3.4
* revision [287383](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287383): add collapsible sections for `Subsequent runs`
* revision [287411](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287411): Clarify multiple outgoing servers and clearly state that non SMTP outgoing servers are not supported as per Martin's comment [below](https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770501)

**Comment by freaktechnik** [comment]
> More than one outgoing server is not supported. 

That doesn't mean we don't show accounts with that, we just only export the outgoing server of the default identity. And that server has to be an SMTP server.

**Comment by rtanglao** [comment]
### Possible tweaks to the design in future builds of Android and Desktop
#### Desktop
* [Compare with the old design](https://assets-prod.sumo.prod.webservices.mozgcp.net/media/uploads/gallery/images/2024-10-23-21-48-15-38e86e.png)
![image](https://github.com/user-attachments/assets/b1699e06-231b-4e58-a0ef-37a19064577e)
#### Android:
* ([Compare with the old design](https://flic.kr/p/2qpCaiy))
![image](https://github.com/user-attachments/assets/89ee3a0d-4613-49d6-af6e-a738b04a6370)


### Figma:
* Desktop design file: https://www.figma.com/design/8cxvWoYZPhzGvphxmfJLaF/TBDesktop_2024_Q3_CrossDevice_v01.0?node-id=6187-1402&t=XNRkNhIQhUvkRXz7-1
* Mobile FTUE design file: https://www.figma.com/design/3Xx6EzwsVgbudJECshgwL2/TBAndroid_2024_Q3_CrossDevice_v01.0?node-id=1-6&t=tIvKUJudzTRPSJJ2-1

**Comment by rtanglao** [comment]
> > More than one outgoing server is not supported.
> 
> That doesn't mean we don't show accounts with that, we just only export the outgoing server of the default identity. And that server has to be an SMTP server.

@freaktechnik:  thanks for the feedback again! Does the wording in revision [287411](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287411) work for you? If not please suggest alternate wording.

**Comment by rtanglao** [comment]
* revision [287576](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287576): import from file
* revision [287616](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287616): fix formatting
* revision [287617](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287617): fix typo with the word `either` :-)

**Comment by cketti** [comment]
> If you have many email accounts, multiple QR codes will be displayed when you scan from your Android device in the next step.

At least one user was confused by the UI. So maybe make this part more explicit. Only one QR code is shown at a time. Users have to press the "Next" (name from memory, please double check) button to display the next QR code.

**Comment by cketti** [comment]
Section: Import the Desktop settings into Thunderbird for Android / First run

> Tap [Import settings] > [Scan QR code]. Scan the QR code from Thunderbird Desktop. If you have many email accounts, after scanning the first QR code, another code will be displayed and scanned until all account settings have been setup. 

1. If users use the primary button ("Import settings"), there's no additional button. QR code scanning (or the permission check prior to that) will start immediately. Pressing the "Scan QR code" button is only necessary if they enter the import screen via the "Import your account settings now" button at the bottom (we probably don't want to advertise this way of getting to the QR code scanner).
2. There's no automatic QR code switching. Once a user has scanned a QR code the "Scanned X of Y" counter will increase and users have to manually advance to the next QR code on desktop (the Android app will keep scanning).

**Comment by cketti** [comment]
Section: How To Import email account settings using a settings file from Thunderbird or K-9 / Export Thunderbird or K-9 settings to a file

> If you have accounts that are not using [OAuth](https://wikipedia.org/wiki/OAuth) and you wish to export your passwords, you will see a Security section. Tick Include all accounts passwords under Security to export your passwords to a file.

The Android apps currently don't support exporting passwords via the export to file option.

**Comment by rtanglao** [comment]
* Revision [287632](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287632): Document: [The Android apps currently don't support exporting passwords via the export to file option.](https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770571)
* Revision [287650](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287650): Fix: Section: Import the Desktop settings into Thunderbird for Android / First run as per https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770560, Scanned 1 of 2 on Android and then click Next on Desktop and then Import on Android and also Done on Desktop which generates an Export summary: screen showing: # of QR codes generated, detailed list of accounts exported, whether or not passwords were exported with an Export more accounts button on the bottom left.
* revision [287651](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287651): Clarify: [only 1 QR code is shown at a time](https://github.com/thunderbird/knowledgebase-issues/issues/158#issuecomment-4078770551)

**Comment by rtanglao** [comment]
* revision [287770](https://support.mozilla.org/en-US/kb/thunderbird-android-import/revision/287770): import from K-9 requires K-9 8.0 or later
* revision [287779](https://support.mozilla.org/en-US/kb/thunderbird-android-8-faq/revision/287779): a few typos and remove mention of a specific date

**Comment by freaktechnik** [comment]
I was asked to point out [Bug 1928234 - QR code colors can get inverted in high contrast mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1928234), since Thunderbird for Android currently fails to scan QR codes when this happens, so you'd have to disable high contrast mode to make it work atm. [EDIT by roland]: see also  [Can't import accounts in Thunderbird app using QR code #8506 ](https://github.com/thunderbird/thunderbird-android/issues/8506) <-- solution: switch Desktop to light theme, real fix in 128.4.2 or maybe 128.4.3

**Comment by kewisch** [comment]
@rtanglao not sure if it fits into this article, but it would be great to somewhere add some troubleshooting steps that I can share in the bugtracker in case people have questions. We have 8464 on tfa for example which is a hodge podge of people having issues, so super hard to manage.

Some rough ideas:
* Scan the thing with another qr code scanner to see if it works
* Check the text from the other scanner to see if there are some invalid fields, such as `null` - if so this is a desktop bug and needs to be filed
* Light mode or disabling HCM, as above
* Different distances from the qr code

Maybe you have a few more ideas in addition.

**Comment by rtanglao** [comment]
* See also: [QR Code to Import Settings Will Not Scan #8464](https://github.com/thunderbird/thunderbird-android/issues/8464) and [QR-Code doesn't work #8520](https://github.com/thunderbird/thunderbird-android/issues/8520)

**Comment by rtanglao** [comment]
* looks like we only support the back-facing camera not the front-facing camera which may be a problem with Chromebooks and other devices that only have 1 camera that  appears a front-facing camera to Android: [Rafael believes per Matrix discussion on #Thunderbird Mobile Development](https://matrix.to/#/!OunCTcAqvhPaYBwOTH:mozilla.org/$fezynPOEqyLb-13cm4hxLR1DWCAm3jm78zpCpoU4rVA?via=int21.dev&via=matrix.org&via=mozilla.org) regarding SUMO question [1542788](https://support.mozilla.org/en-US/questions/1542788): `So, this is likely the reason. I need to double-check the code, but usually QR code scanners only use the device's back camera. I will try to reproduce that using an emulator, as I don't have a device without a back camera`
    * see also [Support Chromebooks in your camera app](https://developer.android.com/media/implement/surfaces/support-chromebooks-in-your-camera-app)
